remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Open Food, in Architect
description: Create a meaningful dialogue with your food.
